### ISSUE TITLE
ansible-test-utility-container image does not having power support

### ISSUE THREAD

**Issue by ashwinik30** [ansible/ansible-test-utility-container#3]
Description:
The ansible-test-utility-container does not having power ppc64le support

Expected :
Should have power support

actual :
Dependent tests failing which used below image
https://quay.io/repository/ansible/ansible-test-utility-container?tab=tags&tag=2.0.0

**Comment by mattclay** [comment]
Closing, since this is being tracked under https://github.com/ansible/ansible/issues/80548.
